
namespace GroupDocs.Editor.WebForms
{
    public partial class Startup {
        // Action generated by the FrameWork - required for compilation
        public void Configuration() {
           
        }
    }
}
